### ISSUE TITLE
The Sourceforge lastest version download for 3.016 is not working

### ISSUE THREAD

**Issue by abmclin** [DaveVoorhis/Rel#11]
When I follow https://sourceforge.net/projects/dbappbuilder/files/Rel/ and click on the green "Download Latest Version" button, I get this error "**Unable to find any mirror information for the "/Rel/Rel version 3.016/Rel3.016.windows.zip" file. Please select another file.**"

When I look under the Rel parent directory, I see several folders corresponding to versions of the Rel system, the numbers only go up to 3.014. The folder for 3.016 appears to be missing.

**Comment by DaveVoorhis** [comment]
I assume that’s a SourceForge issue, as the folder for 3.016 is there. I see it at https://sourceforge.net/projects/dbappbuilder/files/Rel/Rel%20version%203.016/

 

I wonder if SourceForge is adding/updating/changing mirrors and some haven’t fully updated yet. 

 

From: Alexander McLin ***@***.***> 
Sent: 19 January 2023 16:02
To: DaveVoorhis/Rel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DaveVoorhis/Rel] The Sourceforge lastest version download for 3.016 is not working (Issue #11)

 

When I follow https://sourceforge.net/projects/dbappbuilder/files/Rel/ and click on the green "Download Latest Version" button, I get this error "Unable to find any mirror information for the "/Rel/Rel version 3.016/Rel3.016.windows.zip" file. Please select another file."

When I look under the Rel parent directory, I see several folders corresponding to versions of the Rel system, the numbers only go up to 3.014. The folder for 3.016 appears to be missing.

**Comment by abmclin** [comment]
Indeed that seems to be the case, the download link is now working again. I guess it's like that saying about weather, if one don't like it, just wait a little while, then it'll change. I'll close the issue, sorry about the noise.
