### ISSUE TITLE
Command Line interface on Mac OS Sonoma

### ISSUE THREAD

**Issue by cedricniyi** [DaveVoorhis/Rel#13]
Hello, 
I'm using Rel to practice Tutorial D for one of my university courses. I'm using MacOS (Sonoma) to run Rel but I've noticed that there's something really uncomfortable about the user interface. When my system is in dark mode, I can't see what I'm typing on the command line, it's black text on a black background, the font colour changes between 2 lines...
To be able to see what I need to do, I have to switch my whole system to light mode... I can change the colour of the text in the section above the entry but not the area where the user can write.

Thanks in advance for your help.

<img width="1263" alt="Command Line interface, Dark mode system" src="https://github.com/DaveVoorhis/Rel/assets/90785147/c530948f-ba63-48ba-98d1-ca41c7bbe4fc">

<img width="1126" alt="Command Line interface, Light mode system" src="https://github.com/DaveVoorhis/Rel/assets/90785147/79b0461c-c428-48f2-8964-196a8803625b">

**Comment by DaveVoorhis** [comment]
Supporting dark mode isn't a priority, but I'll look at changing the relevant UI styles to support it at some point.
